# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/39551/Desktop/Stochastic-Computing-for-MNIST/DNN-like Structure/DNN_Stochastic/DNN_Stochastic.srcs/sources_1/ip/weight_fc3/weight_fc3.xci
# IP: The module: 'weight_fc3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39551/Desktop/Stochastic-Computing-for-MNIST/DNN-like Structure/DNN_Stochastic/DNN_Stochastic.gen/sources_1/ip/weight_fc3/weight_fc3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_fc3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/39551/Desktop/Stochastic-Computing-for-MNIST/DNN-like Structure/DNN_Stochastic/DNN_Stochastic.srcs/sources_1/ip/weight_fc3/weight_fc3.xci
# IP: The module: 'weight_fc3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39551/Desktop/Stochastic-Computing-for-MNIST/DNN-like Structure/DNN_Stochastic/DNN_Stochastic.gen/sources_1/ip/weight_fc3/weight_fc3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_fc3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
