# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/39551/Desktop/Stochastic_Computing/CNN/CNN.srcs/sources_1/ip/bram_fcweight/bram_fcweight.xci
# IP: The module: 'bram_fcweight' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39551/Desktop/Stochastic_Computing/CNN/CNN.gen/sources_1/ip/bram_fcweight_1/bram_fcweight_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fcweight'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/39551/Desktop/Stochastic_Computing/CNN/CNN.srcs/sources_1/ip/bram_fcweight/bram_fcweight.xci
# IP: The module: 'bram_fcweight' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39551/Desktop/Stochastic_Computing/CNN/CNN.gen/sources_1/ip/bram_fcweight_1/bram_fcweight_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fcweight'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
